2025-06-28 13:20:27,020 - aiogram.dispatcher - INFO - Start polling
2025-06-28 13:20:27,235 - aiogram.dispatcher - INFO - Run polling for bot @eWork_Robot id=7554067474 - 'eWork_Robot'
2025-06-28 13:20:42,037 - aiogram.event - INFO - Update id=762863126 is not handled. Duration 640 ms by bot id=7554067474
2025-06-28 13:20:42,037 - aiogram.event - ERROR - Cause exception while process update id=762863126 by bot id=7554067474
TelegramBadRequest: Telegram server says - Bad Request: inline keyboard button Web App URL 'https://localhost:8000/users/index/' is invalid: Wrong HTTP URL
Traceback (most recent call last):
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\ework_bot_tg\bot\bot.py", line 150, in cmd_start
    await message.answer(
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\client\bot.py", line 478, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ostro\OneDrive\Рабочий стол\Django_proj\Ework\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: inline keyboard button Web App URL 'https://localhost:8000/users/index/' is invalid: Wrong HTTP URL
2025-06-28 13:20:53,042 - aiogram.dispatcher - INFO - Polling stopped
2025-06-28 13:20:53,310 - aiogram.dispatcher - INFO - Polling stopped for bot @eWork_Robot id=7554067474 - 'eWork_Robot'
2025-06-28 13:21:56,220 - aiogram.dispatcher - INFO - Start polling
2025-06-28 13:21:56,440 - aiogram.dispatcher - INFO - Run polling for bot @eWork_Robot id=7554067474 - 'eWork_Robot'
2025-06-28 13:21:57,883 - aiogram.event - INFO - Update id=762863127 is handled. Duration 687 ms by bot id=7554067474
2025-06-28 13:26:35,018 - aiogram.event - INFO - Update id=762863128 is handled. Duration 250 ms by bot id=7554067474
